### ISSUE TITLE
CONTROL INTERFACE - Joystick/Throttle Safety Point

### ISSUE THREAD

**Issue by Michael-Equi** [JHSRobo/ROSbasic#120]
Add safety point that turns off the thrusters if the throttle or joystick is unplugged

**Comment by caelinsutch** [comment]
Joy package has auto repeat built in, I'll enable it

**Comment by Michael-Equi** [comment]
How does that solve the issue?

**Comment by Michael-Equi** [comment]
The issue is closer to what we had with the autonomous car where if the joystick diconects it does not default to a safe mode.

**Comment by caelinsutch** [comment]
@Michael-Equi wouldn't auto repeat help? If it repeats at a set interval, have a program that detects that if a new message isn't published after a set period of time, it turns on safe mode. @CallMeJai can you weigh in too.

**Comment by Michael-Equi** [comment]
That is not how the joystick works

**Comment by ajgrinds** [comment]
Yeah stoopid

**Comment by Michael-Equi** [comment]
Its periodic not continuous data stream. This is a super petty issue to be working with right now. But the way to do it is to monitor the dmesg output for connections and disconnections.

**Comment by caelinsutch** [comment]
Thank you Andrew isn't helpful. You can set it to continuous that's what I'm saying @Michael-Equi and @ajgrinds

**Comment by Michael-Equi** [comment]
This is the message when connecting a joystick

[31551.741004] usb 1-1: new low-speed USB device number 6 using xhci_hcd
[31551.914653] usb 1-1: New USB device found, idVendor=046d, idProduct=c215
[31551.914658] usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[31551.914662] usb 1-1: Product: Logitech Extreme 3D
[31551.914666] usb 1-1: Manufacturer: Logitech
[31552.495443] input: Logitech Logitech Extreme 3D as /devices/pci0000:00/0000:00:14.0/usb1/1-1/1-1:1.0/0003:046D:C215.0003/input/input142
[31552.553159] logitech 0003:046D:C215.0003: input,hidraw2: USB HID v1.10 Joystick [Logitech Logitech Extreme 3D] on usb-0000:00:14.0-1/input0


This is the message when disconnecting the joystick

[31630.710405] usb 1-1: USB disconnect, device number 6

We can use this for joystick/throttle information as well so that we do not need to plug them in in any specific order

**Comment by caelinsutch** [comment]
That would be good for #42

**Comment by caelinsutch** [comment]
I added it as a comment there

**Comment by caelinsutch** [comment]
@Michael-Equi one of the parameters listed is:

```
~autorepeat_rate 
type = double 
default = 0.0 (disabled) 
Rate in Hz at which a joystick that has a non-changing state will resend the previously sent message.
```

[Joy Package from ROS](http://wiki.ros.org/joy)

**Comment by Michael-Equi** [comment]
Test its beahivior

**Comment by caelinsutch** [comment]
I don't have a joystick since the lab suckied up all of them. Can someone bring me one tomorrow @Michael-Equi @CallMeJai @ajgrinds

**Comment by ajgrinds** [comment]
How would we bring you one? I don't have any other than the lab.

**Comment by caelinsutch** [comment]
```
6,1260,16210219074,-;input: Logitech Logitech Extreme 3D as /devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2:1.0/0003:046D:C215.0006/input/input18
6,1261,16210277297,-;logitech 0003:046D:C215.0006: input,hidraw2: USB HID v1.10 Joystick [Logitech Logitech Extreme 3D] on usb-0000:00:14.0-2/input0
 SUBSYSTEM=hid
 DEVICE=+hid:0003:046D:C215.0006
6,1262,16210540551,-;usb 1-2: USB disconnect, device number 8
 SUBSYSTEM=usb
 DEVICE=c189:7
```
