### ISSUE TITLE
ROSDep Error

### ISSUE THREAD

**Issue by caelinsutch** [JHSRobo/ROSbasic#129]
Spits out following error after running `rosdep install --from-paths src --ignore-src --rosdistro kinetic -y`

```
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
launch_files: Cannot locate rosdep definition for [rosserial-arduino]
```

**Comment by Michael-Equi** [comment]
should be fixed just check to make sure all the right packages are installed by rosdep in order to run topside and bottomside on a fresh machine (with ros installed but no extra deps)

**Comment by caelinsutch** [comment]
Checked on dev, closing issue
