### ISSUE TITLE
HOTFIX-vector drive out of range values

### ISSUE THREAD

**Issue by CallMeJai** [JHSRobo/ROSbasic#134]
Twisting the joystick and moving it to some corners causes the cmd_horizontal_vdrive node to output values greater than 1000 or less than -1000

**Comment by Michael-Equi** [comment]
Is this with or without PIDs. Make sure any vector drive calcs are done before normalization.

**Comment by CallMeJai** [comment]
Without PIDs, although PIDs may have the same issue

**Comment by Michael-Equi** [comment]
some missing abs
